name: Bug Report
description: Create a report to help us improve FC Clubs
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please search existing issues first.
  
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "When I tap on X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device & iOS Version
      description: e.g. iPhone 15 Pro, iOS 18.2
      placeholder: iPhone 15 Pro, iOS 18.1
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: App Version
      description: Check the bottom of the Settings screen.
      options:
        - v1.0.0
        - v1.0.1 (TestFlight)
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or logs to help explain your problem.
