name: Bug Report
description: Report an issue
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What went wrong? How can we reproduce it?
      placeholder: "I tapped on the Club tab and the app crashed..."
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device & iOS Version
      placeholder: iPhone 15 Pro, iOS 18.2
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs (Optional)
