name: Feature Request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: What feature would you like to see?
      placeholder: "I want to be able to see match history for..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: How would this help you?
